/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14/samples
 * This project uses @Incubating APIs which are subject to change.
 */
subprojects {
    apply(plugin = "java")

    group = "es.mpoea.fair-manager"
    description = "Service for managing fairs"
    version = "1.0.0"

    extensions.configure<JavaPluginExtension> {
        toolchain.languageVersion.set(JavaLanguageVersion.of(25))
    }

    repositories {
        mavenCentral()
    }

    tasks.withType<Test>().configureEach {
        useJUnitPlatform()
    }
}